# .github/actions/create-secret/action.yml
name: 'Create Repository Secret'
description: 'Creates a secret in the repository with given name and value'
inputs:
  secret_name:
    description: 'The name of the secret'
    required: true
  secret_value:
    description: 'The value of the secret'
    required: true
  org_name:
    description: 'The name of the organization of repository'
    required: true
  repo_name:
    description: 'The name of the repository'
    required: true
  AUTH_TOKEN:
    description: 'Token to create secret'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Create Repository Secret
      run: |
        python3 -m pip install PyNaCl
        python3 -m pip install pybase64
        chmod +x ./scripts/copy-update-secrets-repo.sh
        ./scripts/copy-update-secrets-repo.sh
      env:
        AUTH_TOKEN: ${{ inputs.AUTH_TOKEN }}
        ORG_NAME: ${{ inputs.org_name }}
        REPO_NAME: ${{ inputs.repo_name }}
        SECRET_NAME: ${{ inputs.secret_name }}
        SECRET_VALUE: ${{ inputs.secret_value }}
      shell: bash
