# .github/actions/create-variables/action.yml
name: 'Create Repository Variable'
description: 'Creates repository variables with given name and value'
inputs:
  var_name:
    description: 'The name of the variable'
    required: true
  var_value:
    description: 'The value of the variable'
    required: true
  repo_name:
    description: 'The value of the variable'
    required: true
  AUTH_TOKEN:
    description: 'Token to create repo variable'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create repository variable
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ inputs.AUTH_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ inputs.repo_name }}/actions/variables \
          -d '{"name":"'"${{ inputs.var_name }}"'","value":"'"${{ inputs.var_value }}"'"}'
      shell: bash
