name: Show Contexts

on:
  workflow_dispatch

jobs:
  Show-Listed-Contexts:
    runs-on: ubuntu-latest
    steps:
    - name: Github Context
      run: echo '${{ toJSON(github) }}'

    - name: Github Context
      run: echo '${{ toJSON(job) }}'

    - name: Github Context
      run: echo '${{ toJSON(steps) }}'

    - name: Github Context
      run: echo '${{ toJSON(runner) }}'

    - name: Github Context
      run: echo '${{ toJSON(secrets) }}'
